# version: '1'

services:
  db:
    # container_name: db-container
    build: 
      context: .
      dockerfile: Dockerfiles/mysql/Dockerfile
    volumes:
    - /var/lib/mysql
    ports:
      - "3306:3306"
  php:
    # container_name: php-container
    build: 
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    # depends_on:
    #   db:
    #     condition: service_completed_successfully
    links:
      - db
